name: 'Push to Redocly'

on:
  push:
    branches:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Push files and wait for deployment'
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'visionaryx'
          project: 'visionaryx'
          mountPath: '/products/api-hub/Learning API'
          files: 'index.md learning.yaml logo.jpg'
          domain: 'https://app.cloud.redocly.com'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}
